import { NextResponse } from 'next/server'

export async function GET() {
  const recommendations = [
    {
      rank: 1,
      symbol: '000660',
      name: 'SK하이닉스',
      market: 'KR',
      sector: '반도체',
      price: 185000,
      changePct: 3.2,
      score: 94,
      grade: 'S',
      rsi: 22.1,
      maStatus: '골든크로스 발생!',
      bbPosition: '하단 이탈',
      bbWidth: 4.2,
      volumeRatio: 4.5,
      per: 7.8,
      pbr: 1.2,
      roe: 28.5,
      operatingGrowth: 145,
      foreignNetBuy: 2340,
      institutionNetBuy: 890,
      foreignOwnership: 52.3,
      macd: { value: 1250, signal: 980, histogram: 270 },
      stochastic: { k: 12, d: 15 },
      recommendation: '🔥 최강 매수 — 트리플 시그널',
      expectedReturn: '+20~35%',
      profitPotential: 97,
      riskLevel: 'LOW',
      riskScore: 6,
      targetPrice: 222000,
      stopLoss: 172000,
      signals: [
        {
          type: 'bullish',
          indicator: 'RSI',
          description:
            'RSI 22.1 — 극단적 과매도! 최근 5년 중 최저. 반등 확률 92%',
          confidence: 95,
        },
        {
          type: 'bullish',
          indicator: 'MA-GC',
          description:
            '⭐ 골든크로스 발생 + 정배열 진입! 역사적 평균 +23.4% 상승',
          confidence: 88,
        },
        {
          type: 'bullish',
          indicator: 'BB',
          description: '볼린저 하단 이탈 후 복귀 시작 — 스퀴즈(4.2%) 해소 임박',
          confidence: 82,
        },
        {
          type: 'bullish',
          indicator: 'OBV',
          description: '거래량 4.5배 폭증 + 상승 — 외국인/기관 동시 대량 매집',
          confidence: 90,
        },
        {
          type: 'bullish',
          indicator: 'FLOW',
          description: '외국인 +2,340억 + 기관 +890억 동반 순매수 5일 연속!',
          confidence: 92,
        },
        {
          type: 'bullish',
          indicator: 'FUND',
          description:
            'PER 7.8배(업종 15배) + ROE 28.5% + 영업이익 +145% — 극단적 저평가',
          confidence: 88,
        },
        {
          type: 'bullish',
          indicator: 'STOCH',
          description: '스토캐스틱 K=12 — 극단적 과매도, 반전 임박',
          confidence: 80,
        },
        {
          type: 'bullish',
          indicator: 'MACD',
          description: 'MACD 히스토그램 양전환 시작 — 상승 모멘텀 전환',
          confidence: 78,
        },
      ],
      aiAnalysis:
        '🏆 10개 분석 지표 중 8개가 강력 매수 시그널을 보여주는 극히 드문 "퍼펙트 스톰" 패턴입니다.\n\n핵심 근거:\n1. HBM3E 독점 공급: NVIDIA GB200 서버 1대당 HBM 36개 탑재. 2026년 글로벌 HBM 시장 $38B 중 SK하이닉스 점유율 53%\n2. 실적 폭발: 2026 Q1 영업이익 7.2조원 전망 (컨센서스 상회 예상). HBM 매출 비중 40% 돌파\n3. 기술적 바닥: RSI 22는 최근 5년 중 2번만 나타난 수치. 두 번 모두 3개월 내 평균 +28.7% 상승\n4. 수급 쏠림: 외국인+기관 5일 연속 3,000억원+ 순매수는 대형 랠리 전조\n\n리스크: 미중 반도체 규제 강화 시 수출 제한 가능성 (확률 15%)',
      historicalPattern:
        '과거 RSI<25 + 골든크로스 동시 발생 시: 3개월 평균 +28.7% (5회 중 5회 상승, 승률 100%)',
      catalysts: [
        'HBM3E 양산 본격화 (Q2)',
        'NVIDIA GB200 출하 시작',
        'Q1 실적 발표 (4월)',
        '자사주 매입 프로그램',
      ],
    },
    {
      rank: 2,
      symbol: 'NVDA',
      name: 'NVIDIA',
      market: 'US',
      sector: 'AI 반도체',
      price: 875.3,
      changePct: 4.5,
      score: 91,
      grade: 'S',
      rsi: 27.8,
      maStatus: '정배열 (강한 상승)',
      bbPosition: '하단 터치',
      bbWidth: 5.1,
      volumeRatio: 3.8,
      per: 32.5,
      pbr: 18.2,
      roe: 85.3,
      operatingGrowth: 210,
      foreignNetBuy: 0,
      institutionNetBuy: 0,
      foreignOwnership: 0,
      macd: { value: 15.2, signal: 12.1, histogram: 3.1 },
      stochastic: { k: 18, d: 22 },
      recommendation: '🔥 최강 매수 — AI 패권',
      expectedReturn: '+15~30%',
      profitPotential: 95,
      riskLevel: 'MID',
      riskScore: 9,
      targetPrice: 1100,
      stopLoss: 810,
      signals: [
        {
          type: 'bullish',
          indicator: 'RSI',
          description: 'RSI 27.8 — 과매도. 조정 후 반등 포인트',
          confidence: 88,
        },
        {
          type: 'bullish',
          indicator: 'FUND',
          description: 'ROE 85.3% — 세계 최고 수익성. 영업이익 +210%',
          confidence: 92,
        },
        {
          type: 'bullish',
          indicator: 'OBV',
          description: '기관 대량 매수 포착. 거래량 3.8배',
          confidence: 85,
        },
        {
          type: 'bullish',
          indicator: 'AI',
          description: 'AI GPU 독점 + Blackwell 출하 + 데이터센터 CAPEX 폭증',
          confidence: 90,
        },
        {
          type: 'bullish',
          indicator: 'MACD',
          description: 'MACD 히스토그램 양전환 — 하락 모멘텀 소진',
          confidence: 78,
        },
      ],
      aiAnalysis:
        '🌍 AI 인프라 슈퍼사이클의 절대 수혜주. Blackwell GPU가 Hopper 대비 30배 AI 추론 성능을 제공하며, 2026년 데이터센터 GPU 시장 점유율 92% 유지 전망.\n\nMeta/Google/Microsoft/Amazon의 AI CAPEX 합산 $200B+ 중 상당 부분이 NVIDIA GPU로 향함. 현재 PER 32.5배는 ROE 85%를 감안하면 역사적 저평가 구간.\n\n리스크: AMD MI400 경쟁, 미중 수출 규제 확대',
      historicalPattern:
        'NVIDIA RSI<30 발생 시: 3개월 평균 +22.1% (최근 4회 중 4회 상승)',
      catalysts: [
        'Blackwell Ultra 발표 (GTC)',
        'Q1 실적 가이던스',
        '소버린 AI 수요 확대',
        'Omniverse 상용화',
      ],
    },
    {
      rank: 3,
      symbol: '005930',
      name: '삼성전자',
      market: 'KR',
      sector: '반도체/전자',
      price: 72500,
      changePct: 1.8,
      score: 86,
      grade: 'A+',
      rsi: 28.5,
      maStatus: '골든크로스 임박 (D-2)',
      bbPosition: '하단 터치',
      bbWidth: 3.8,
      volumeRatio: 2.8,
      per: 11.2,
      pbr: 1.1,
      roe: 12.8,
      operatingGrowth: 78,
      foreignNetBuy: 1560,
      institutionNetBuy: 420,
      foreignOwnership: 55.1,
      macd: { value: -180, signal: -250, histogram: 70 },
      stochastic: { k: 22, d: 28 },
      recommendation: '⭐ 강력 매수 관심',
      expectedReturn: '+12~22%',
      profitPotential: 88,
      riskLevel: 'LOW',
      riskScore: 12,
      targetPrice: 86000,
      stopLoss: 67500,
      signals: [
        {
          type: 'bullish',
          indicator: 'RSI',
          description: 'RSI 28.5 — 과매도. 52주 최저 근접',
          confidence: 82,
        },
        {
          type: 'bullish',
          indicator: 'MA-GC',
          description: '골든크로스 D-2 임박! 5MA가 20MA에 수렴 중',
          confidence: 76,
        },
        {
          type: 'bullish',
          indicator: 'FUND',
          description: 'PER 11.2배(10년 평균 14배) — 30% 할인',
          confidence: 80,
        },
        {
          type: 'bullish',
          indicator: 'FLOW',
          description: '외국인 +1,560억 순매수 3일 연속',
          confidence: 78,
        },
        {
          type: 'bullish',
          indicator: 'BB',
          description: '볼린저 하단 터치 + 밴드 스퀴즈 3.8%',
          confidence: 72,
        },
      ],
      aiAnalysis:
        '삼성전자 PER 11.2배는 10년 평균 14배 대비 20% 할인된 저평가 구간. HBM3E 양산 본격화 + 파운드리 수율 개선 + Galaxy AI 탑재 스마트폰 판매 호조.\n\n외국인이 3일 연속 1,500억원+ 순매수하는 패턴은 최근 3년간 7회 발생, 이 중 6회(86%)에서 1개월 내 +8% 이상 상승.',
      historicalPattern:
        '삼성전자 RSI<30 + 외국인 순매수 패턴: 1개월 평균 +11.3% (7회 중 6회 상승)',
      catalysts: ['HBM3E 양산', '파운드리 2nm GAA', 'Q1 실적', '자사주 소각'],
    },
    {
      rank: 4,
      symbol: 'AAPL',
      name: 'Apple',
      market: 'US',
      sector: '빅테크',
      price: 198.5,
      changePct: 2.1,
      score: 79,
      grade: 'A+',
      rsi: 34.2,
      maStatus: '상승 전환',
      bbPosition: '하단 근접',
      bbWidth: 4.5,
      volumeRatio: 2.3,
      per: 28.1,
      pbr: 42.5,
      roe: 147.2,
      operatingGrowth: 12,
      foreignNetBuy: 0,
      institutionNetBuy: 0,
      foreignOwnership: 0,
      macd: { value: -1.2, signal: -2.5, histogram: 1.3 },
      stochastic: { k: 28, d: 32 },
      recommendation: '⭐ 강력 매수 관심',
      expectedReturn: '+10~18%',
      profitPotential: 82,
      riskLevel: 'LOW',
      riskScore: 18,
      targetPrice: 228,
      stopLoss: 185,
      signals: [
        {
          type: 'bullish',
          indicator: 'RSI',
          description: 'RSI 34.2 — 매수 관심 구간 진입',
          confidence: 72,
        },
        {
          type: 'bullish',
          indicator: 'FUND',
          description: 'ROE 147% — 세계 최고 자본효율성. 서비스 매출 역대 최대',
          confidence: 85,
        },
        {
          type: 'bullish',
          indicator: 'MACD',
          description: 'MACD 히스토그램 양전환 — 하락 모멘텀 소진',
          confidence: 74,
        },
        {
          type: 'bullish',
          indicator: 'OBV',
          description: '거래량 2.3배 — 기관 매수세 유입',
          confidence: 70,
        },
      ],
      aiAnalysis:
        'Apple Intelligence 기반 iPhone 교체 사이클 + 서비스 매출 비중 25% 돌파. Vision Pro 생태계 확장. 연간 $100B+ 자사주 매입으로 주주환원 최강.',
      historicalPattern: 'Apple PER<30 진입 시: 6개월 평균 +14.8%',
      catalysts: [
        'iPhone 17 발표',
        'WWDC Apple Intelligence 2.0',
        'India 생산 확대',
        '서비스 매출 신기록',
      ],
    },
    {
      rank: 5,
      symbol: '035420',
      name: 'NAVER',
      market: 'KR',
      sector: 'AI/플랫폼',
      price: 215000,
      changePct: 0.9,
      score: 72,
      grade: 'A',
      rsi: 38.1,
      maStatus: '상승 추세',
      bbPosition: '밴드 내',
      bbWidth: 5.8,
      volumeRatio: 1.8,
      per: 22.5,
      pbr: 1.8,
      roe: 8.5,
      operatingGrowth: 15,
      foreignNetBuy: 320,
      institutionNetBuy: 180,
      foreignOwnership: 43.2,
      macd: { value: 850, signal: 720, histogram: 130 },
      stochastic: { k: 42, d: 45 },
      recommendation: '✅ 매수 관심',
      expectedReturn: '+8~15%',
      profitPotential: 74,
      riskLevel: 'MID',
      riskScore: 26,
      targetPrice: 245000,
      stopLoss: 200000,
      signals: [
        {
          type: 'bullish',
          indicator: 'RSI',
          description: 'RSI 38.1 — 매수 관심 구간',
          confidence: 68,
        },
        {
          type: 'bullish',
          indicator: 'FLOW',
          description: '외국인 +320억 + 기관 +180억 순매수',
          confidence: 72,
        },
        {
          type: 'bullish',
          indicator: 'AI',
          description: 'HyperCLOVA X 상용화 + 네이버 클라우드 AI 성장',
          confidence: 75,
        },
      ],
      aiAnalysis:
        'HyperCLOVA X 기반 B2B AI 서비스 본격 매출화. 네이버 검색 AI 전환으로 광고 단가 상승. 웹툰 글로벌 1위 + 커머스 성장.',
      historicalPattern: 'NAVER RSI 35~40 매수 시: 3개월 평균 +9.2%',
      catalysts: [
        'HyperCLOVA X 엔터프라이즈',
        '네이버 클라우드 AI',
        '웹툰 글로벌 확장',
      ],
    },
    {
      rank: 6,
      symbol: 'TSLA',
      name: 'Tesla',
      market: 'US',
      sector: 'EV/AI',
      price: 245.3,
      changePct: -0.5,
      score: 63,
      grade: 'B+',
      rsi: 44.3,
      maStatus: '횡보',
      bbPosition: '밴드 내',
      bbWidth: 8.2,
      volumeRatio: 1.5,
      per: 58.2,
      pbr: 11.5,
      roe: 21.3,
      operatingGrowth: -8,
      foreignNetBuy: 0,
      institutionNetBuy: 0,
      foreignOwnership: 0,
      macd: { value: -3.5, signal: -2.8, histogram: -0.7 },
      stochastic: { k: 45, d: 48 },
      recommendation: '👀 관심 종목',
      expectedReturn: '+5~20%',
      profitPotential: 65,
      riskLevel: 'HIGH',
      riskScore: 37,
      targetPrice: 295,
      stopLoss: 220,
      signals: [
        {
          type: 'neutral',
          indicator: 'RSI',
          description: 'RSI 44.3 — 중립, 방향 대기',
          confidence: 55,
        },
        {
          type: 'bullish',
          indicator: 'AI',
          description: 'FSD + 로보택시 + 옵티머스 로봇 — 비선형 성장 잠재력',
          confidence: 65,
        },
      ],
      aiAnalysis:
        'FSD(완전자율주행) 상용화 여부가 Tesla 가치의 핵심. 로보택시 서비스 런칭 시 시가총액 $2T 이상 가능하나, 실패 시 단순 EV 업체 밸류(현재 대비 -30%). 고위험 고수익 종목.',
      historicalPattern: 'Tesla 횡보 후 방향 전환 시: 평균 ±25% 급변동',
      catalysts: [
        '로보택시 서비스 런칭',
        'FSD v13 출시',
        '저가 EV 모델 2 발표',
        '옵티머스 로봇 시연',
      ],
    },
  ]
  return NextResponse.json(recommendations)
}
