import { NextResponse } from 'next/server'

export async function GET() {
  const recommendations = [
    {
      rank: 1,
      symbol: '000660',
      name: 'SK하이닉스',
      market: 'KR',
      price: 185000,
      changePct: 3.2,
      score: 87,
      grade: 'A+',
      rsi: 28.5,
      maStatus: '골든크로스',
      bbPosition: '하단 터치',
      volumeRatio: 2.8,
      recommendation: '강력 매수 관심',
      signals: [
        {
          type: 'bullish',
          indicator: 'RSI',
          description: 'RSI 28.5 — 과매도 구간',
        },
        { type: 'bullish', indicator: 'MA', description: '골든크로스 발생!' },
        {
          type: 'bullish',
          indicator: 'BB',
          description: '볼린저 하단 터치 — 반등 가능',
        },
        { type: 'bullish', indicator: 'VOL', description: '거래량 2.8배 급증' },
      ],
    },
    {
      rank: 2,
      symbol: '005930',
      name: '삼성전자',
      market: 'KR',
      price: 72500,
      changePct: 1.8,
      score: 78,
      grade: 'A',
      rsi: 35.2,
      maStatus: '상승 추세',
      bbPosition: '밴드 내',
      volumeRatio: 1.9,
      recommendation: '매수 관심',
      signals: [
        {
          type: 'bullish',
          indicator: 'RSI',
          description: 'RSI 35.2 — 매수 관심',
        },
        {
          type: 'bullish',
          indicator: 'MA',
          description: '상승 추세 (5MA > 20MA)',
        },
        { type: 'bullish', indicator: 'MOM', description: '당일 +1.8% 상승' },
      ],
    },
    {
      rank: 3,
      symbol: 'AAPL',
      name: 'Apple',
      market: 'US',
      price: 198.5,
      changePct: 2.1,
      score: 74,
      grade: 'A',
      rsi: 42.1,
      maStatus: '상승 추세',
      bbPosition: '밴드 내',
      volumeRatio: 2.3,
      recommendation: '매수 관심',
      signals: [
        {
          type: 'bullish',
          indicator: 'MA',
          description: '상승 추세 (5MA > 20MA)',
        },
        { type: 'bullish', indicator: 'VOL', description: '거래량 2.3배 급증' },
      ],
    },
    {
      rank: 4,
      symbol: '035720',
      name: '카카오',
      market: 'KR',
      price: 45800,
      changePct: -1.2,
      score: 65,
      grade: 'B+',
      rsi: 38.7,
      maStatus: '중립',
      bbPosition: '하단 근접',
      volumeRatio: 1.1,
      recommendation: '관심 종목',
      signals: [
        {
          type: 'bullish',
          indicator: 'RSI',
          description: 'RSI 38.7 — 매수 관심',
        },
        { type: 'neutral', indicator: 'MA', description: '횡보 추세' },
      ],
    },
    {
      rank: 5,
      symbol: 'TSLA',
      name: 'Tesla',
      market: 'US',
      price: 245.3,
      changePct: -0.5,
      score: 62,
      grade: 'B+',
      rsi: 44.3,
      maStatus: '중립',
      bbPosition: '밴드 내',
      volumeRatio: 1.5,
      recommendation: '관심 종목',
      signals: [
        { type: 'neutral', indicator: 'RSI', description: 'RSI 44.3 — 중립' },
        { type: 'bullish', indicator: 'VOL', description: '거래량 1.5배 증가' },
      ],
    },
    {
      rank: 6,
      symbol: 'MSFT',
      name: 'Microsoft',
      market: 'US',
      price: 425.8,
      changePct: 0.8,
      score: 58,
      grade: 'B',
      rsi: 52.1,
      maStatus: '상승 추세',
      bbPosition: '밴드 내',
      volumeRatio: 0.9,
      recommendation: '중립 — 관망',
      signals: [
        { type: 'neutral', indicator: 'RSI', description: 'RSI 52.1 — 중립' },
        { type: 'bullish', indicator: 'MA', description: '상승 추세' },
      ],
    },
  ]
  return NextResponse.json(recommendations)
}
