import { NextResponse } from 'next/server'

export async function GET() {
  const leaderboard = [
    {
      rank: 1,
      nickname: 'QuantKing',
      tier: 'pro',
      strategy: 'AI 분석',
      totalReturn: 34.5,
      winRate: 72.3,
      trades: 234,
      followers: 156,
      mdd: -8.2,
      sharpe: 2.1,
    },
    {
      rank: 2,
      nickname: 'ValueHunter',
      tier: 'pro',
      strategy: 'MACD',
      totalReturn: 28.7,
      winRate: 68.1,
      trades: 189,
      followers: 98,
      mdd: -11.5,
      sharpe: 1.8,
    },
    {
      rank: 3,
      nickname: 'TrendRider',
      tier: 'basic',
      strategy: 'MA 크로스오버',
      totalReturn: 22.1,
      winRate: 65.4,
      trades: 312,
      followers: 87,
      mdd: -9.8,
      sharpe: 1.5,
    },
    {
      rank: 4,
      nickname: 'GridMaster',
      tier: 'pro',
      strategy: '그리드 트레이딩',
      totalReturn: 19.8,
      winRate: 78.2,
      trades: 456,
      followers: 64,
      mdd: -5.3,
      sharpe: 1.9,
    },
    {
      rank: 5,
      nickname: 'RSI_Pro',
      tier: 'basic',
      strategy: 'RSI',
      totalReturn: 17.3,
      winRate: 62.8,
      trades: 167,
      followers: 52,
      mdd: -12.1,
      sharpe: 1.3,
    },
    {
      rank: 6,
      nickname: 'BollingerFan',
      tier: 'pro',
      strategy: '볼린저밴드',
      totalReturn: 15.9,
      winRate: 61.5,
      trades: 198,
      followers: 41,
      mdd: -10.7,
      sharpe: 1.2,
    },
    {
      rank: 7,
      nickname: 'SafeTrader',
      tier: 'basic',
      strategy: 'MA 크로스오버',
      totalReturn: 12.4,
      winRate: 58.9,
      trades: 89,
      followers: 33,
      mdd: -6.4,
      sharpe: 1.4,
    },
    {
      rank: 8,
      nickname: 'AITrader',
      tier: 'pro',
      strategy: 'AI 분석',
      totalReturn: 11.8,
      winRate: 57.2,
      trades: 145,
      followers: 28,
      mdd: -14.3,
      sharpe: 1.0,
    },
  ]
  return NextResponse.json(leaderboard)
}
